#!/sbin/openrc-run

description="Coraza WAF SPOA daemon for HAProxy"
command="/usr/bin/coraza-spoa"
cfgfile="${cfgfile:-/etc/coraza-spoa/config.yaml}"
command_args="-config $cfgfile"
command_user="coraza-spoa:coraza-spoa"
command_background="yes"
pidfile="/var/run/coraza-spoa.pid"
output_log="/var/log/coraza-spoa/stdout.log"
error_log="/var/log/coraza-spoa/stderr.log"

depend()
{
	need net
	use logger
}
