#!/bin/sh

pkgname=github-cli
pkgver=2.101.0
pkgrel=1
pkgarch=${SAPHIRA_ARCH:-x86_64}
pkgdesc='GitHub CLI (gh): command-line interface to GitHub'
license='MIT'
origin=github-cli
repo=saphira
url=https://github.com/cli/cli
source=https://github.com/cli/cli/archive/refs/tags/v2.101.0.tar.gz
sha256=a266fe8575c0e061b987920c1831a15f71bf0036a8729a5ebb93c2fb0164899c
# Go toolchain lock (operator requirement): v2.101.0 declares
# go 1.27.0 / toolchain go1.27.1; Saphira ships go 1.27.0-r1.
# GOTOOLCHAIN=local pins the build to the repository toolchain and
# the build fails closed if the language level ever exceeds it -
# never an automatic toolchain download.
# Module tree is NOT vendored (age precedent): the release tarball
# is pinned and modules resolve in the worker (GOFLAGS=-mod=mod,
# GOCACHE/GOPATH/GOBIN under BUILDDIR). Static musl binary
# (CGO_ENABLED=0), GOAMD64=v3 per the Saphira baseline.
# gh shells out to git for repository operations.

depends="git"
makedepends="
	go
	make
"

subpackages="$pkgname-doc"

recipe_build()
{
	echo "$sha256  $RECIPE_DIR/files/v2.101.0.tar.gz" | sha256sum -c -
	tar --no-same-owner -C "$SRC" --strip-components=1 -xf "$RECIPE_DIR/files/v2.101.0.tar.gz"
	mkdir -p "$BUILDDIR"
	export GOCACHE="$BUILDDIR/.gocache" GOPATH="$BUILDDIR/.gopath" GOBIN="$BUILDDIR/.gobin"
	export GOFLAGS=-mod=mod CGO_ENABLED=0 GOTOOLCHAIN=local GOAMD64=v3
	# NOTE: -trimpath must NOT go in GO_LDFLAGS (linker rejects it;
	# upstream script/build.go already passes -trimpath itself).
	export GO_LDFLAGS='-buildid='
	export GH_VERSION=2.101.0
	export PATH="$GOBIN:$PATH"
	cd "$SRC"
	# Populate the module cache first (go.mod/go.sum are complete;
	# -mod=mod keeps them so under the locked toolchain).
	go mod download
	# Third-party licence report BEFORE the final binary: it is
	# embedded via go:embed, and without it `gh licenses` serves
	# only the placeholder. Installs pinned go-licenses into GOBIN.
	./script/licenses linux amd64
	# Build through upstream's own machinery so Version/Date
	# ldflags are stamped exactly as releases do.
	go build -o "$BUILDDIR/script-build" ./script
	"$BUILDDIR/script-build" bin/gh
	"$BUILDDIR/script-build" manpages
	# Completions generated by the freshly built binary (upstream
	# `completions` target, staged under BUILDDIR instead of share/).
	mkdir -p "$BUILDDIR/completions"
	"$SRC/bin/gh" completion -s bash > "$BUILDDIR/completions/gh.bash"
	"$SRC/bin/gh" completion -s fish > "$BUILDDIR/completions/gh.fish"
	"$SRC/bin/gh" completion -s zsh > "$BUILDDIR/completions/_gh"
	# Acceptance smoke before staging: exact version string.
	"$SRC/bin/gh" --version | grep -qx 'gh version 2.101.0.*' || {
		echo "ERROR: unexpected version output" >&2
		"$SRC/bin/gh" --version >&2
		return 1
	}
	"$SRC/bin/gh" licenses | grep -q 'License information is only available' && {
		echo "ERROR: licence report is the placeholder" >&2
		return 1
	}
	echo "gh build OK: $("$SRC/bin/gh" --version)"
}

recipe_install()
{
	install -D -m 0755 "$SRC/bin/gh" "$PKGDEST/usr/bin/gh"
	install -d "$PKGDEST/usr/share/man/man1"
	install -m 0644 "$SRC"/share/man/man1/gh*.1 "$PKGDEST/usr/share/man/man1/"
	install -D -m 0644 "$BUILDDIR/completions/gh.bash" \
		"$PKGDEST/usr/share/bash-completion/completions/gh"
	install -D -m 0644 "$BUILDDIR/completions/gh.fish" \
		"$PKGDEST/usr/share/fish/vendor_completions.d/gh.fish"
	install -D -m 0644 "$BUILDDIR/completions/_gh" \
		"$PKGDEST/usr/share/zsh/site-functions/_gh"
	install -D -m 0644 "$BUILDDIR/completions/_gh" \
		"$PKGDEST/usr/share/zsh/vendor-completions/_gh"
	install -D -m 0644 "$SRC/LICENSE" \
		"$PKGDEST/usr/share/licenses/github-cli/LICENSE"
}
