#!/sbin/openrc-run

description="ClamAV antivirus scanner daemon"

command="/usr/sbin/clamd"
command_args="--foreground=true"
supervisor="supervise-daemon"
command_user="clamav:clamav"

depend()
{
	use net logger dns
	after clamav-freshclam
}

start_pre()
{
	checkpath -d -o clamav:clamav -m 0750 /var/run/clamav /var/log/clamav
	checkpath -d -o clamav:clamav -m 0755 /var/lib/clamav
	ebegin "Checking clamd configuration"
	out=$(/usr/sbin/clamd --config-file=/etc/clamav/clamd.conf --check-config 2>&1) ||
		eend 1 "$out"
	eend 0
}
