clamav {
    type = "clamav";
    symbol = "CLAM_VIRUS";
    servers = "/run/clamav/clamd.ctl";

    scan_mime_parts = true;
    scan_text_mime = false;
    scan_image_mime = false;

    max_size = 52428800;
    timeout = 10.0;
    retransmits = 2;

    action = "reject";
    message = 'ZeroDNS Mail System: message rejected. Antivirus scanning detected malware signature "${VIRUS}" using ${SCANNER}. For safety, this email was not accepted or delivered.';


    log_clean = false;

    patterns {
        JUST_EICAR = '^Eicar-Test-Signature$';
    }
}
