use = [
    "authentication-results",
    "x-spamd-result",
    "x-spamd-bar",
    "x-spam-status"
];

extended_spam_headers = true;

skip_local = false;
skip_authenticated = false;

extended_headers_rcpt = [
    "@akadata.ltd",
    "@az2.co.uk",
    "@breathcard.co.uk",
    "@breathtechnology.co.uk",
    "@zerodns.co.uk"
];

routines {
    x-spamd-result {
        header = "X-Spamd-Result";
        remove = 0;
        sort_by = "score";
    }

    x-spam-status {
        header = "X-Spam-Status";
        remove = 0;
    }

    x-spamd-bar {
        header = "X-Spamd-Bar";
        remove = 0;
        positive = "+";
        negative = "-";
        neutral = "/";
    }
}
