AZ2_MESSAGE_TYPE {
    type = "header";
    header = "X-AZ2-Message-Type";
    map = "$CONFDIR/local.d/maps.d/az2_message_types.map";
    score = 0.0;
    description = "Known AZ2 application message type";
}
