@version: 4.12

source s_sys {
	unix-stream("/dev/log");
	file("/proc/kmsg" program_override("kernel: "));
	internal();
};

destination d_messages { file("/var/log/messages"); };

log { source(s_sys); destination(d_messages); };
